### ISSUE TITLE
query about  accelerometer data  (offset correction and unit conversion)

### ISSUE THREAD

**Issue by ihtishamaliktk** [CIFASIS/dataset-processing#2]
Hi, 
 The Accelerometer offset  correction [926.447738516  -15.4401130742 -401.003545936] used in the  _imu_convertion.py_  is different than the offset given in the calibration file which is [24.13, 4.88, -24.93]. 
Is there any unit conversion that  I am missing?

Secondly, the raw data format says that accelerometer values are in _mg_ (milli-g). Shouldn't then _mg_ be first converted to _g_ and then to m/s<sup>2</sup> in  _imu_convertion.py_?

Thank you

**Comment by taihup** [comment]
Hi,
the valid values are those in the yaml configuration file. Please see the function `modify_imu_data() `inside `create_bagfile.py` script. There you can check how the offset is applied and how the unit conversion is done.

Note: We found some issues related to the IMU measurements (they are not uniformly distributed as it is expected (caused by how we recorded the data) and there are some moments where the IMU gives null measurements with white noise (seems to be a hardware issue in the TARA). We are working on solving these issues and we are going to update the dataset soon (we don't have an estimated date but should be in the next months).

**Comment by ihtishamaliktk** [comment]
I missed going through `create_bagfile.py`. Its more informative. Thank you
Best of luck with the imu data fix.

**Comment by impce-lg** [comment]
@taihup hi buddy, may i ask where are u about the dataset update?

**Comment by taihup** [comment]
Hi guys, we are still working on it, I will post here when we upload the fixed data.

**Comment by impce-lg** [comment]
@taihup hi bro, is the dataset availible now?

**Comment by taihup** [comment]
Not yet. We will post here as soon as there is news.

**Comment by kzamzam** [comment]
@taihup  are the bag files available on the website created using the create_bagfile.py. So they contain rectified images, and also the IMU values are already processed for the biases?

**Comment by taihup** [comment]
The script create_bagfile.py removes the IMU bias (check function `modify_imu_data()`) and rectified the images (check function `rectify_images()`).

**Comment by kzamzam** [comment]
@taihup I think the create_bagfile.py does not actually rectify the images, it just gets the P matrix needed for that and adds it to the camera_info topic, however, the rectification itself is not applied.

**Comment by taihup** [comment]
I think you are right, the images are not recitified but the rectify information is stores in camera_info
